import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { Geist, Geist_Mono } from 'next/font/google'

import '~/styles/globals.css'

const geistSans = Geist({
	subsets: ['latin'],
	variable: '--font-geist-sans'
})

const geistMono = Geist_Mono({
	subsets: ['latin'],
	variable: '--font-geist-mono'
})

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
			className={`${geistSans.variable} ${geistMono.variable} h-full whitespace-pre-line antialiased`}
		>
			<body className='bg-background text-foreground flex min-h-full flex-col'>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}

export const viewport = {
	initialScale: 1,
	maximumScale: 1,
	themeColor: [
		{ color: '#f7f7f7', media: '(prefers-color-scheme: light)' },
		{ color: '#14120b', media: '(prefers-color-scheme: dark)' }
	],
	userScalable: false,
	width: 'device-width'
}
